# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_auto_20170906_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default='1970-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
