# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0003_auto_20170906_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
    ]
