# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_source_to_existing_posts(apps, schema_editor):
    # query the app to get all the existing posts
    Post = apps.get_model('flash', 'Post')
    Source = apps.get_model('flash','Source')
    for post in Post.objects.all():
        new_source = post.url
        var_list = new_source.split("/")
        if var_list[2]:
            real_source = var_list[2]
        else:
            real_source = var_list[0]
        try:
            match = Source.objects.get(base_url=real_source)
        except Source.DoesNotExist:
            match = None
        if match:
            post.source = match
            post.save()
        else:
            add_source = Source.objects.create(base_url=real_source, title=real_source)
            post.source = add_source
            post.save()



class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0004_remove_author_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flash.Source'),
        ),
        migrations.RunPython(add_source_to_existing_posts),
    ]
